# Workflow's name
name: linux-clang

# Run this workflow every time a new commit pushed to your repository
on: [push, pull_request]

jobs:
  linux-clang:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Installing premake5
        uses: Jarod42/install-premake5@v3
      - name: Build
        run: |
          premake5 add --package=https://github.com/sniper00/lrust.git
          premake5 build --release
          premake5 publish
          zip_name=$(ls *.zip)
          echo "zip_name=$zip_name" >> $GITHUB_ENV
      - name: Test
        run: |
          chmod +x target/release/moon
          premake5 run --release example/test/main_test.lua