
# Workflow's name
name: windows-vs2022

# Run this workflow every time a new commit pushed to your repository
on: [push, pull_request]

jobs:
  windows-vs2022:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Installing premake5
        uses: Jarod42/install-premake5@v3
      - name: setup msbuild
        uses: microsoft/setup-msbuild@v1.1
      - name: Build
        run: |
          premake5 add --package=https://github.com/sniper00/lrust.git
          premake5 build --release
          premake5.exe publish
          pwsh -command '$env:zip_name = (Get-ChildItem -Filter *.zip).Name; echo "zip_name=$env:zip_name" >> $env:GITHUB_ENV'
      - name: Test
        run: premake5 run --release example/test/main_test.lua

